import ast
import builtins


def _existing_ast_types(*names):
    return {
        node for name in names if (node := ast.__dict__.get(name)) is not None
    }


ALLOWED_BUILTINS = {
    "Exception",
    "False",
    "None",
    "True",
    "abs",
    "all",
    "any",
    "ascii",
    "bin",
    "bool",
    "bytearray",
    "bytes",
    "chr",
    "dict",
    "divmod",
    "filter",
    "float",
    "format",
    "frozenset",
    "hex",
    "int",
    "isinstance",
    "issubclass",
    "import",
    "len",
    "list",
    "map",
    "max",
    "min",
    "oct",
    "ord",
    "pow",
    "range",
    "reversed",
    "round",
    "set",
    "sorted",
    "str",
    "sum",
    "tuple",
    "zip",
}

ILLEGAL_BUILTINS = set(dir(builtins)) - ALLOWED_BUILTINS

ALLOWED_AST_TYPES = {
    ast.Module,
    ast.Constant,
    ast.Name,
    ast.Attribute,
    ast.Load,
    ast.Store,
    ast.Starred,
    ast.FunctionDef,
    ast.Return,
    ast.Assign,
    ast.AugAssign,
    ast.For,
    ast.While,
    ast.If,
    ast.Assert,
    ast.Pass,
    ast.Import,
    ast.Expr,
    ast.Global,
    ast.BoolOp,
    ast.BinOp,
    ast.UnaryOp,
    ast.Compare,
    ast.Call,
    ast.keyword,
    ast.arguments,
    ast.arg,
    ast.alias,
    ast.Add,
    ast.Sub,
    ast.Mult,
    ast.Div,
    ast.Mod,
    ast.Pow,
    ast.USub,
    ast.Not,
    ast.And,
    ast.Or,
    ast.Eq,
    ast.NotEq,
    ast.Lt,
    ast.LtE,
    ast.Gt,
    ast.GtE,
    ast.In,
    ast.NotIn,
    ast.Is,
    ast.IsNot,
    ast.Dict,
    ast.List,
    ast.Set,
    ast.Tuple,
    ast.Subscript,
    ast.Slice,
    ast.ListComp,
    ast.comprehension,
} | _existing_ast_types("Index")

ILLEGAL_AST_TYPES = {
    ast.AsyncFor,
    ast.AsyncFunctionDef,
    ast.AsyncWith,
    ast.Await,
    ast.ClassDef,
    ast.GeneratorExp,
    ast.ImportFrom,
    ast.Interactive,
    ast.Lambda,
    ast.MatMult,
    ast.Nonlocal,
    ast.Try,
    ast.With,
    ast.Yield,
    ast.YieldFrom,
} | _existing_ast_types("Ellipsis", "Suite")

ALLOWED_ANNOTATION_TYPES = {
    "Any",
    "bool",
    "datetime.datetime",
    "datetime.timedelta",
    "dict",
    "float",
    "int",
    "list",
    "str",
}
