from pathlib import Path

RECURSION_LIMIT = 1024

DELIMITER = ":"
INDEX_SEPARATOR = "."

SUBMISSION_CONTRACT_NAME = "submission"
PRIVATE_METHOD_PREFIX = "__"
EXPORT_DECORATOR_STRING = "export"
INIT_DECORATOR_STRING = "construct"
INIT_FUNC_NAME = "__{}".format(PRIVATE_METHOD_PREFIX)
VALID_DECORATORS = {EXPORT_DECORATOR_STRING, INIT_DECORATOR_STRING}

ORM_CLASS_NAMES = {
    "Variable",
    "Hash",
    "ForeignVariable",
    "ForeignHash",
    "LogEvent",
}

MAX_HASH_DIMENSIONS = 16
MAX_KEY_SIZE = 1024

READ_COST_PER_BYTE = 1
WRITE_COST_PER_BYTE = 25
TRANSACTION_BYTES_COST_PER_BYTE = READ_COST_PER_BYTE
RETURN_VALUE_COST_PER_BYTE = READ_COST_PER_BYTE
MAX_RETURN_VALUE_SIZE = 1024 * 128
MAX_CONTRACT_SUBMISSION_BYTES = 64 * 1024
DEPLOYMENT_BASE_COST = 5_000
DEPLOYMENT_COST_PER_SOURCE_BYTE = 1
ZK_VERIFY_GROTH16_BASE_COST = 750_000
ZK_VERIFY_GROTH16_PER_PUBLIC_INPUT_COST = 50_000
ZK_VERIFY_GROTH16_PER_PAYLOAD_BYTE_COST = 50
ZK_VERIFY_GROTH16_REGISTRY_BASE_COST = 500_000
ZK_VERIFY_GROTH16_REGISTRY_PREPARE_COST = 250_000
ZK_VERIFY_GROTH16_REGISTRY_PER_PUBLIC_INPUT_COST = 50_000
ZK_VERIFY_GROTH16_REGISTRY_PER_PAYLOAD_BYTE_COST = 25
ZK_SHIELDED_TREE_APPEND_BASE_COST = 250_000
ZK_SHIELDED_TREE_APPEND_PER_COMMITMENT_COST = 500_000
ZK_SHIELDED_COMMAND_NULLIFIER_DIGEST_BASE_COST = 100_000
ZK_SHIELDED_COMMAND_NULLIFIER_DIGEST_PER_INPUT_COST = 50_000
ZK_SHIELDED_COMMAND_BINDING_COST = 100_000
ZK_SHIELDED_COMMAND_EXECUTION_TAG_COST = 50_000
MAX_ZK_VERIFYING_KEY_HEX_CHARS = 8_192
MAX_ZK_PROOF_HEX_CHARS = 4_096
MAX_ZK_PUBLIC_INPUTS = 32
MAX_ZK_VERIFYING_KEY_ID_CHARS = 128
ZK_REGISTRY_CONTRACT_NAME = "zk_registry"

CHI_PER_T = 20

BLOCK_NUM_DEFAULT = -1
FILENAME_LEN_MAX = 255

DEFAULT_CHI = 1000000
TRANSACTION_BASE_CHI = 5

STORAGE_HOME = Path().home().joinpath(".cometbft/xian")
